### ISSUE TITLE
Netlify's version of this package is outdated (still on 1.0.4)

### ISSUE THREAD

**Issue by dabrady** [bencao/netlify-plugin-inline-functions-env#15]
In my `package.json`, I have the latest version of this plugin installed, which is v1.0.5:
```json
  "devDependencies": {
    ...
    "netlify-plugin-inline-functions-env": "^1.0.5",
    ...
  }

```
And everything was working fine on my deploy previews. But as soon as I tried a production deploy, the build failed because I'm using the `buildEvent` input, which was added in v1.0.5, but for some reason Netlify is using v1.0.4:
![image](https://user-images.githubusercontent.com/2475919/95694083-05b0be80-0bfe-11eb-9240-9b511fd1db1a.png)

My guess is that since I do not have this plugin as a production dependency, Netlify is falling back to whatever version is in it's own plugin repository, and I'm guessing that version is out of date.

My current workaround has been to make this a production dependency, which allows it to take precedence over whatever is in Netlify's repository, and works:
![image](https://user-images.githubusercontent.com/2475919/95694410-e61a9580-0bff-11eb-992c-4092cb011aca.png)

**Comment by bencao** [comment]
Thanks for reporting!
I just published a new version of 1.0.6 and will request an updated in netlify's plugin repo and it will become the default version that netlify use.

**Comment by bencao** [comment]
This is the related PR in netlify/plugins repo https://github.com/netlify/plugins/pull/151

**Comment by dabrady** [comment]
Thanks a lot! 🙏

**Comment by tysonmatanich** [comment]
@bencao looks like Netlify is waiting on you to resolve a Node 10 compatibility issue https://github.com/bencao/netlify-plugin-inline-functions-env/issues/16.

**Comment by tysonmatanich** [comment]
🎉 Netlify now has 1.0.8. Issue should be able to be closed.

**Comment by bencao** [comment]
since netlify already merged the version upgrade PR, this issue may be considered as done ,although I noticed the recent runs for my projects still uses v1.0.4.

@ehmicky would you mind help clarify when would the new version take effect in production for all projects that did not add the plugin to their devDependencies?

**Comment by ehmicky** [comment]
Hi @bencao!
At the moment, new plugin versions are released each time we make a new release of our build system, which is typically around once per week, so this should be updated soon. We are also currently working on possible solutions to remove this delay altogether so that users get the new plugin version as soon as you've updated its version in `netlify/plugins`.
